#!/usr/bin/python
import sys
try:
    import zmugfs
except ImportError:
    print >> sys.stderr, """\
There was a problem importing one of the Python modules
required to run zmugfs. The error leading to this problem was:

   %s

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
%s

""" % (sys.exc_value, sys.version)
    sys.exit(1)

try:
    zmugfs.main(sys.argv[1:])
except KeyboardInterrupt, e:
    print >> sys.stderr, "\n\nExiting on user cancel."
    sys.exit(1)
